language: java
jdk: oraclejdk8
env:
  global:
    secure: ypDN/T91zwXjRAT7aNM52ICZzF/9yyJDFocfs2WUP4VDR2p1cXX5uadzcrlQCaUc0TAuICPdosceegjQHdr7uB0ozNa+BVOBAqYVR0/v0zHd2D5aq8fSpgaw7yJMjwXeUEakmi1XXti+yj0OrYguNWttEg8xARwVV5MhlAhN/FFysdQvpwUuZnjDjsZ0fIkOXKGJPOjOLs5afOe7oD2wr2lKKKcn4Dx4ulCNtRDdQZJaHPZtHaIxlZX0QLvV2N3pJqJGbzwyJCts27asHaEmj6e3rw7hRTZXXeWZKVypINnjv17nMRtAXJkbu5wsu5QHCeILDVDJ/jsA0Ztrua7OGtpthVAhmU7u58b7iqcIFzL95LcM+visRp24y27d8frJxxEFW4KhxmPtIuHpvUqH9cGQ34eTaKppVDawOzcaTFDlYc+WQIHopKP0bTpMwYoMaZUUhRAppbTscfNdhBsAnsarAnzsx1ypFhjrE279eF/01oPx6+3Lzf5dXDYrrSs9Ey6PQ7PEi7fWy8XzKt7ypOwHIQ6Ys7OPYEx+AwUHo2l1UZJtRh7Zv+3+xNDjkKRta1/pp8UBwLV5U59FBAGGTdlAScUoU+y+Ue/zqhrdHTmI4ne60bWbyPoj18J2ValDVEfucTw3HUSL+w8aaI9HXHRYHKd4bX2mjj1adWT3wTU=
install: gradle assemble -x signArchives
script: gradle build -x signArchives
after_success: tools/deploy-javadoc.sh
